window.PROJECTS = [
  {
    slug: "rhytuals",
    sourcePage: "asset/rhytuals/",
    title: "Rhytuals",
    categories: ["designerpage"],
    date: "2025",
    info: [
      "Field<br>Research<br>Editorial design",
      "Team<br>Giulia Bonalumi<br>Federico Gajo<br>Enrico Isidori<br>Francesco Scarfone<br>Ekaterina Shults<br>Camilla Tosi",
    ],
    description:
      "Rhytuals explores how rhythm structures social behavior and transforms collective actions into rituals.\nIt examines rhythm’s role in shaping identity, community, and resistance, revealing its power as a unifying force across cultures and histories.\nThe chapters of the magazine unfold simultaneously on the same pages. A non-conventional reading method that allows each page to be turned multiple times with completely different rhythms depending on the chapter.",
    media: [
      {
        type: "image",
        src: "asset/rhytuals/optimized/r-0.webp",
        width: 1361,
        height: 1700,
      },
      {
        type: "image",
        src: "asset/rhytuals/optimized/r-1.webp",
        width: 1361,
        height: 1700,
      },
      {
        type: "video",
        src: "asset/rhytuals/image/02-motion-optimized.mp4",
        unmute: false,
      },
      {
        type: "image",
        src: "asset/rhytuals/optimized/r-2.webp",
        width: 652,
        height: 1700,
      },
      {
        type: "image",
        src: "asset/rhytuals/optimized/r-3.webp",
        width: 1361,
        height: 1700,
      },
      {
        type: "image",
        src: "asset/rhytuals/optimized/r-4.webp",
        width: 1361,
        height: 1700,
      },
      {
        type: "image",
        src: "asset/rhytuals/optimized/r-5.webp",
        width: 1361,
        height: 1700,
      },
      {
        type: "image",
        src: "asset/rhytuals/optimized/r-6.webp",
        width: 1361,
        height: 1700,
      },
      {
        type: "image",
        src: "asset/rhytuals/optimized/r-7.webp",
        width: 1361,
        height: 1700,
      },
      {
        type: "image",
        src: "asset/rhytuals/optimized/r-8.webp",
        width: 1361,
        height: 1700,
      },
      {
        type: "image",
        src: "asset/rhytuals/optimized/r-9.webp",
        width: 1361,
        height: 1700,
      },
      {
        type: "image",
        src: "asset/rhytuals/optimized/r-10.webp",
        width: 1361,
        height: 1700,
      },
      {
        type: "image",
        src: "asset/rhytuals/optimized/r-11.webp",
        width: 1361,
        height: 1700,
      },
      {
        type: "image",
        src: "asset/rhytuals/optimized/r-12.webp",
        width: 1361,
        height: 1700,
      },
      {
        type: "video",
        src: "asset/rhytuals/image/r-14-optimized.mp4",
        unmute: false,
      },
    ],
  },
  {
    slug: "off-discipline",
    sourcePage: "offdisicpline/",
    title: "Off Discipline",
    categories: ["designerpage"],
    date: "2026",
    info: [
      "Field<br>Research<br>Editorial design",
      'Link<br><a href="https://enricoisidori.com/overtrace" target="_blank" rel="noopener noreferrer">enricoisidori.com/overtrace</a>',
    ],
    description:
      "Design is an anomalous discipline. This volume explores the “off” character of design against disciplinary logics. Design is out-of-place: misplaced because it does not have a stable object of study, inappropriate because this characteristic can subvert the disciplinary norms of other fields. The research is developed through a purpose-built software tool for the progressive tracing of design processes.",
    media: [
      {
        type: "image",
        src: "offdisicpline/asset/optimized/off1.webp",
        width: 1440,
        height: 1920,
      },
      {
        type: "image",
        src: "offdisicpline/asset/optimized/off2.webp",
        width: 1440,
        height: 1920,
      },
      {
        type: "image",
        src: "offdisicpline/asset/optimized/off3.webp",
        width: 1440,
        height: 1920,
      },
      {
        type: "image",
        src: "offdisicpline/asset/optimized/off4.webp",
        width: 1440,
        height: 1920,
      },
      {
        type: "image",
        src: "offdisicpline/asset/optimized/off5.webp",
        width: 1439,
        height: 1920,
      },
      {
        type: "image",
        src: "offdisicpline/asset/optimized/off6.webp",
        width: 1439,
        height: 1920,
      },
      {
        type: "image",
        src: "offdisicpline/asset/optimized/off7.webp",
        width: 1440,
        height: 1920,
      },
      {
        type: "image",
        src: "offdisicpline/asset/optimized/off8.webp",
        width: 1440,
        height: 1920,
      },
      {
        type: "image",
        src: "offdisicpline/asset/optimized/off9.webp",
        width: 1440,
        height: 1920,
      },
    ],
  },
  {
    slug: "image-of-a-book",
    sourcePage: "asset/imageofabook/",
    title: "Image of a book",
    categories: ["artistpage"],
    date: "2024",
    info: [],
    description:
      '10x18x1cm\n\nThis book is unreadable, yet visible and recognizable as such. It exists as an autonomous object in its own right.\nIt is composed of images generated with Stable Diffusion, trained locally on page layouts, then printed and bound.\n\nThe work builds on Giulio Confalonieri\'s 1963 exploration of a book of layered, unreadable texts made from printing waste sheets, which he described as "the image of reading suspended at the stage preceding knowledge."',
    media: [
      {
        type: "image",
        src: "asset/imageofabook/optimized/1.webp",
        width: 1275,
        height: 1700,
      },
      {
        type: "image",
        src: "asset/imageofabook/optimized/2.webp",
        width: 1276,
        height: 1700,
      },
      {
        type: "image",
        src: "asset/imageofabook/optimized/3.webp",
        width: 1700,
        height: 1134,
      },
      {
        type: "image",
        src: "asset/imageofabook/optimized/4.webp",
        width: 1700,
        height: 1430,
      },
      {
        type: "image",
        src: "asset/imageofabook/optimized/4b.webp",
        width: 1275,
        height: 1700,
      },
      {
        type: "video",
        src: "asset/imageofabook/7-optimized.mp4",
        unmute: false,
      },
    ],
  },
  {
    slug: "n-cognitive-supremacy",
    sourcePage: "n+/",
    title: "N+ Cognitive Supremacy",
    categories: ["designerpage", "artistpage"],
    date: "2025",
    info: [
      "Field<br>Speculative design",
      "Role<br>Art direction<br>Branding<br>Spatial design<br>Visual design<br>Interaction design<br>Prototyping<br>Photography",
      "Team<br>Filippo Rosati (creative direction)<br>Pietro Forino (interaction design)<br>Daniela Gentile (research)<br>Nicola Airutti (sound design)<br>Cristina Dezi (fashion design)<br>Bernardo Martins (AI artworks)",
      "Made at<br>Operating System Studio<br>Umanesimo Artificiale",
      'Exhibition<br>Jul 2025<br><a href="https://www.videocitta.com/" target="_blank" rel="noopener noreferrer">Videocittà</a>, Rome<br>Jun 2025<br><a href="https://sonar.es/en" target="_blank" rel="noopener noreferrer">Sónar</a>, Barcelona<br>Apr 2025',
    ],
    description:
      "A non-invasive neural interface developed by N+ Industries to collect\nresidual cognitive activity from the user. Using bone-conducted audio\nstimulation, the system captures neural micro-responses and\nintegrates them into a distributed network. Inspired by a NATO white\npaper stating that “the brain is the new battlefield,” this project\nexplores the intersection of neuroscience and conflict through an\nimmersive and experimental artistic lens. At its core is a pioneering\nenterprise that envisions a future of neuromodulation technologies.\nSpecializing in neuroweapons and NBIC advancements (Nanotechnology,\nBiotechnology, Information Technology, and Cognitive Science), this\nentity develops technologies of control. By presenting these\nunsettling possibilities, the project sparks critical discussions on\nthe future of warfare, human augmentation, and the ethics of cognitive\ncontrol.",
    media: [
      {
        type: "image",
        src: "n+/asset/optimized/n-1.webp",
        width: 1700,
        height: 1133,
      },
      {
        type: "video",
        src: "n+/asset/optimized/wip1-optimized.mp4",
        mobileSrc: "n+/asset/optimized/wip1-mobile.mp4",
        width: 1080,
        height: 1440,
        unmute: false,
      },
      {
        type: "image",
        src: "n+/asset/optimized/n+a.webp",
        width: 1578,
        height: 1700,
      },
      {
        type: "image",
        src: "n+/asset/optimized/n+b.webp",
        width: 1700,
        height: 1054,
      },
      {
        type: "image",
        src: "n+/asset/optimized/wip2.webp",
        width: 1080,
        height: 1440,
      },
      {
        type: "video",
        src: "n+/asset/optimized/wip3-optimized.mp4",
        mobileSrc: "n+/asset/optimized/wip3-mobile.mp4",
        width: 1080,
        height: 1440,
        unmute: false,
      },
      {
        type: "image",
        src: "n+/asset/optimized/adv1.webp",
        width: 1360,
        height: 1700,
      },
      {
        type: "image",
        src: "n+/asset/optimized/adv2.webp",
        width: 1360,
        height: 1700,
      },
      {
        type: "image",
        src: "n+/asset/optimized/adv3.webp",
        width: 1360,
        height: 1700,
      },
      {
        type: "image",
        src: "n+/asset/optimized/adv4.webp",
        width: 1360,
        height: 1700,
      },
      {
        type: "image",
        src: "n+/asset/optimized/adv5.webp",
        width: 1360,
        height: 1700,
      },
      {
        type: "image",
        src: "n+/asset/optimized/adv6.webp",
        width: 1360,
        height: 1700,
      },
      {
        type: "image",
        src: "n+/asset/optimized/adv7.webp",
        width: 1360,
        height: 1700,
      },
      {
        type: "image",
        src: "n+/asset/optimized/n-2.webp",
        width: 1700,
        height: 1134,
      },
      {
        type: "image",
        src: "n+/asset/optimized/n-3.webp",
        width: 1700,
        height: 1133,
      },
      {
        type: "image",
        src: "n+/asset/optimized/n-4.webp",
        width: 1700,
        height: 1133,
      },
      {
        type: "image",
        src: "n+/asset/optimized/n-5.webp",
        width: 1700,
        height: 1133,
      },
      {
        type: "image",
        src: "n+/asset/optimized/n-6.webp",
        width: 1700,
        height: 1133,
      },
      {
        type: "image",
        src: "n+/asset/optimized/n-6-detail.webp",
        width: 1360,
        height: 1700,
      },
      {
        type: "image",
        src: "n+/asset/optimized/n-7.webp",
        width: 1360,
        height: 1700,
      },
      {
        type: "image",
        src: "n+/asset/optimized/n-8.webp",
        width: 1360,
        height: 1700,
      },
    ],
  },
  {
    slug: "digital-forest",
    sourcePage: "digitalforest/",
    title: "Digital Forest",
    categories: ["designerpage"],
    date: "2025",
    info: [
      "Field<br>Information design<br>Data vizualization<br>Spatial design",
      "Team<br>Miguel Ernesto Amaya<br>Federico Gajo<br>Giacomo Garetto<br>Francesco Scarfone<br>Emanuel Simionato",
      '<a href="https://www.meetcenter.it/en" target="_blank" rel="noopener noreferrer">Meet Digital Culture Center 2025, Milan</a>',
      "Exhibited at<br>Cavallerizza Reale 2022, Turin<br>Dock Dora 2022, Turin<br>ELO 2022, Como",
      "Features<br>Nuovi linguaggi del visual design in Italia 2022",
    ],
    description:
      "Trail cams are video cameras triggered by the movement of animals in\ntheir natural habitats. Initially designed for research and wildlife\nmonitoring, they have since become popular content on social media\nplatforms.\nThe installation investigates how animals, inadvertently turned into\ndigital entities, inhabit the online ecosystem—an environment\ncategorized by humans for human consumption.\nThe project examines 273 trail cam videos shared on major Italian\nsocial platforms between 2021 and 2024. The hashtags used at the\ntime of publication establish connections between them. The\ninstallation presents the videos in chronological order, alongside\ntheir associated hashtags, forming a growing network that reflects\nthe evolution of a digital forest—merging human perceptions with\nanimal presence over time.",
    media: [
      {
        type: "image",
        src: "digitalforest/asset/optimized/02.webp",
        width: 1920,
        height: 1371,
      },
      {
        type: "image",
        src: "digitalforest/asset/optimized/01.webp",
        width: 1920,
        height: 1371,
      },
      {
        type: "video",
        src: "digitalforest/asset/03-optimized.mp4",
        unmute: false,
      },
      {
        type: "video",
        src: "digitalforest/asset/04-optimized.mp4",
        unmute: false,
      },
      {
        type: "video",
        src: "digitalforest/asset/05-optimized.mp4",
        unmute: true,
      },
      {
        type: "video",
        src: "digitalforest/asset/06-optimized.mp4",
        unmute: false,
      },
      {
        type: "video",
        src: "digitalforest/asset/07-optimized.mp4",
        unmute: false,
      },
      {
        type: "image",
        src: "digitalforest/asset/optimized/08.webp",
        width: 1920,
        height: 1371,
      },
      {
        type: "video",
        src: "digitalforest/asset/09-optimized.mp4",
        unmute: false,
      },
    ],
  },
  {
    slug: "capsule-plaza",
    sourcePage: "capsule/",
    title: "Capsule Plaza",
    categories: ["designerpage"],
    date: "2023",
    info: [
      "Field<br>Web design<br>Motion design",
      "Team<br>Gabriele Donini<br>Diego Massaro<br>Giacomo Scandolara",
      'Made at<br><a href="https://gigadesignstudio.com/" target="_blank" rel="noopener noreferrer">Giga Design Studio</a>',
      'Links<br><a href="https://capsule.global/plaza" target="_blank" rel="noopener noreferrer">capsule.global/plaza</a>',
    ],
    description:
      "Pop Up Website for Capsule Plaza, an hybrid between a fair and a\ncollective exhibition, it brings together designers and companies\nfrom various creative fields, bridging industry and culture with a\nbold curation that spans interiors and architecture, beauty and\ntechnology, ecology and craft.",
    media: [
      {
        type: "video",
        src: "capsule/asset/desktop-optimized.mp4",
        unmute: false,
        poster: "capsule/asset/optimized/med.webp",
      },
      {
        type: "video",
        src: "capsule/asset/4-optimized.mp4",
        unmute: false,
      },
      {
        type: "video",
        src: "capsule/asset/3-optimized.mp4",
        unmute: false,
      },
      {
        type: "video",
        src: "capsule/asset/2-optimized.mp4",
        unmute: false,
      },
      {
        type: "video",
        src: "capsule/asset/1-optimized.mp4",
        unmute: false,
      },
    ],
  },
  {
    slug: "draw-a-line-from-one-side-of-the-page-to-the-other",
    sourcePage: "drawaline/",
    title: "Draw a line from one side of the page to the other",
    categories: ["designerpage"],
    date: "2022",
    info: [
      "Field<br>Research<br>Editorial design<br>Web design",
      "Team<br>Davide Agostinelli<br>Irene Benecchi<br>Bianca Buratti<br>Alice Dezio<br>Marta Gaggi<br>Giulia Gnessi",
      "Exhibited at<br>Cavallerizza Reale 2022<br>Dock Dora 2022<br>Torino Print Club<br>ELO 2022",
      'Links<br><a href="https://enricoisidori.com/draw.html" target="_blank" rel="noopener noreferrer">enricoisidori.com/draw.html</a>',
      "Features<br>Nuovi linguaggi del visual design in Italia , 2022",
    ],
    description:
      "This book is a collection of strangers’ lines on a blank sheet of paper.\n“Draw a line from one side of the page to the other”, this is the\ninstruction 100 bypassers were given along with the reminder to freely\nexpress themselves on the surface. Where one line ends, another\nbegins—they are individual expressions and a single participatory work.\nTo complete the book, the owner of each copy is asked to draw their own\nline on the cover, thus becoming part of the project. The book has a\nsoundtrack generated by associating the lines with the frequency of the\nsound. By scrolling through the pages and listening to the corresponding\nsound, the reader takes a journey into people’s emotions.",
    media: [
      {
        type: "video",
        src: "drawaline/asset/cover.mp4",
        poster: "drawaline/asset/optimized/cover-poster.webp",
        unmute: false,
      },
      {
        type: "video",
        src: "drawaline/asset/1-optimized.mp4",
        unmute: false,
      },
      {
        type: "video",
        src: "drawaline/asset/2-optimized.mp4",
        unmute: false,
      },
      {
        type: "video",
        src: "drawaline/asset/3-optimized.mp4",
        unmute: false,
      },
      {
        type: "image",
        src: "drawaline/asset/optimized/scan1.webp",
        width: 1434,
        height: 956,
      },
      {
        type: "image",
        src: "drawaline/asset/optimized/scan2.webp",
        width: 1434,
        height: 956,
      },
      {
        type: "image",
        src: "drawaline/asset/optimized/scan3.webp",
        width: 1434,
        height: 956,
      },
      {
        type: "image",
        src: "drawaline/asset/optimized/scan5.webp",
        width: 1434,
        height: 956,
      },
      {
        type: "image",
        src: "drawaline/asset/optimized/scan4.webp",
        width: 1434,
        height: 956,
      },
      {
        type: "image",
        src: "drawaline/asset/optimized/photo1.webp",
        width: 1434,
        height: 956,
      },
      {
        type: "image",
        src: "drawaline/asset/optimized/photo2.webp",
        width: 1434,
        height: 956,
      },
      {
        type: "image",
        src: "drawaline/asset/optimized/photo3.webp",
        width: 1434,
        height: 956,
      },
      {
        type: "image",
        src: "drawaline/asset/optimized/web1.webp",
        width: 1434,
        height: 842,
      },
      {
        type: "image",
        src: "drawaline/asset/optimized/web2.webp",
        width: 1434,
        height: 842,
      },
      {
        type: "image",
        src: "drawaline/asset/optimized/web3.webp",
        width: 1434,
        height: 842,
      },
      {
        type: "image",
        src: "drawaline/asset/optimized/web4.webp",
        width: 1434,
        height: 842,
      },
    ],
  },
  {
    slug: "6am",
    sourcePage: "6am/",
    title: "6AM",
    categories: ["designerpage"],
    date: "2023",
    info: [
      "Field<br>Editorial design",
      "Team<br>Gabriele Donini<br>Federico Gajo<br>Diego Massaro<br>Giacomo Scandolara",
      'Made at<br><a href="https://gigadesignstudio.com/" target="_blank" rel="noopener noreferrer">Giga Design Studio</a>',
      'Links<br><a href="https://6am.glass/" target="_blank" rel="noopener noreferrer">6am.glass</a>',
    ],
    description:
      "Catalog for 6:AM Glassworks: an emerging high-end design brand based in\nMilan, founded in 2018, the brand blends the traditional artisanal\napproach with contemporary design techniques, resulting in artistic\nglass creations.",
    media: [
      {
        type: "image",
        src: "6am/asset/optimized/1.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "6am/asset/optimized/2.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "6am/asset/optimized/3.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "6am/asset/optimized/4.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "6am/asset/optimized/5.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "6am/asset/optimized/6.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "6am/asset/optimized/7.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "video",
        src: "6am/asset/6am1-optimized.mp4",
        unmute: false,
      },
      {
        type: "video",
        src: "6am/asset/6am2-optimized.mp4",
        unmute: false,
      },
    ],
  },
  {
    slug: "specta-thesis",
    sourcePage: "spectathesis/",
    title: "SPECTA® (Thesis)",
    categories: ["designerpage"],
    date: "2023",
    info: [
      "Field<br>Research<br>Editorial design",
      "Team<br>Francesco Bonetti<br>Federico Gajo<br>Emiliano Garibaldi<br>Cecilia Pizzagalli<br>Camilla Tosi",
      'Related projects<br><a href="specta/">SPECTA® (Project)</a>',
      "Made at<br>Politecnico di Milano<br>Laboratorio di Sintesi Finale C1",
      'Links<br><a href="specta.pdf" target="_blank" rel="noopener noreferrer">SPECTA.pdf (Complete Thesis)</a>',
    ],
    description:
      '"Specta è frutto di un processo creativo durato sei mesi che ha coinvolto diversi ambiti: branding, gra-\nfica, coding, ux design, interaction design, video making, prototipazione, copywriting, foto-\ngrafia, web design, packaging design etc. È stata una progettazione complessa: nei seguenti\nparagrafi verrà districato il tempo e lo spazio progettuale che è stato attraversato.\nSarà esaminato il progetto dal punto di vista temporale, della sequenza delle azioni, del processo ana-\nlizzando i modelli e la loro classificazione; e dal punto di vista spaziale, del perimetro delle\ndiscipline, dell’ambito analizzando le mappature il loro rapporto interdisciplinare. Il design è\ntanto uno stato, un oggetto fermo, un artefatto nello spazio, quanto un verbo, un’azione, un\nprocesso che si sviluppa nel tempo (Doblin, 1987).\nLa volontà di questo elaborato è restituire quella che è stata l’esperienza di progetto in quanto vero e\nproprio laboratorio – una sperimentazione progettuale.\nLo scopo di questo capitolo è mettere alla prova la teoria attraverso un progetto, Specta, e proporre un\nmodello frutto di questa esperienza" (p.10)',
    media: [
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis1.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "video",
        src: "spectathesis/asset/spectathesis-optimized.mp4",
        unmute: false,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis2.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis3.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis4.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis5.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis6.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis7.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis8.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis9.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis10.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis11.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis12.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis13.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis14.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis15.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis16.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis17.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis18.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis19.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis20.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "spectathesis/asset/optimized/thesis21.webp",
        width: 1920,
        height: 1280,
      },
    ],
  },
  {
    slug: "specta",
    sourcePage: "specta/",
    title: "SPECTA®",
    categories: ["designerpage"],
    date: "2023",
    info: [
      "Field<br>Speculative<br>Graphic<br>Identity<br>Interaction<br>Packaging<br>Copywriting<br>Photography<br>Video Making<br>Coding<br>Product",
      "Team<br>Francesco Bonetti<br>Federico Gajo<br>Emiliano Garibaldi<br>Cecilia Pizzagalli<br>Camilla Tosi",
      "Made at<br>Politecnico di Milano<br>Laboratorio di Sintesi Finale C1",
      'Related projects<br><a href="specta/">SPECTA® (Thesis)</a>',
      'Links<br><a href="specta.pdf" target="_blank" rel="noopener noreferrer">SPECTA.pdf (Complete Thesis)</a>',
      'Exhibithion<br>Interdependence, Fabbrica del Vapore, Milan, Apr 2024<br>Anthropogenic Narratives, <a href="https://triennale.org" target="_blank" rel="noopener noreferrer">Triennale Milano</a>, Milan, Mar 2023',
      "Features<br>Pittogramma , 2024<br>CDSA Adwards International Media Art Creativity Competition, 2024",
    ],
    description:
      "Specta è un progetto nato durante il Laboratorio di Sintesi Finale C1\ndel Politecnico di Milano, nell’an- no accademico 2022–2023. É stato\nesposto, insieme agli altri progetti del Laboratorio1, in Triennale\nMilano nella mostra Anthropogenic Narratives: Communicating and\nExperiencing Non-human perspectives. Il lavoro si colloca tra le aree\nprogettuali della speculazione, della comunicazione e dell’interazione.\nLa speculazione, ovvero l’individuazione di scenari di possibili futuri,\nla comunicazione, in particolare la costruzione di un brand e di un\nsistema di identità e l’interazione ossia la creazione di interfacce\nfisiche e digitali. Queste aree del design sono state affrontate\nattraverso l’esplorazione dei temi di progetto e la realizzazione\nconcreta del dispositivo. Il brief di progetto del Laboratorio prevede\nlo sviluppo di un dispositivo interattivo – una macchina comunicativa.\nQuesta deve fare emergere le problematiche legate al cambiamento\nclimatico attuale, dal punto di vista di un elemento naturale, nel caso\ndi Specta, le rocce. L’obiettivo è veicolare il messaggio dell’elemento\nattraverso l’interazione con il dispositivo e il linguaggio visivo del\nbrand che lo ha prodotto nello scenario. Specta adotta il linguaggio\ndelle rocce per trattare temi come anti-ecocentrismo, eco-ansia e\nautocensura. L’obiettivo principale di questo progetto è quello di\nstimola- re lo spettatore a riflettere sull’attuale crisi climatica e le\nsue conseguenza sociali. Attraverso lo scenario si cerca di ampliare la\nprospettiva temporale dell’osservatore sul tema. In un presente\ninverosimile in cui, per sospensione dell’incredulità, le rocce hanno la\ncapacità di comunicare messaggi sul cambiamento climatico, esse\ncercherebbero di convincerci che bisogna essere come loro – indifferenti\n– invitandoci a non guardare e a non provare ansia di fronte a quello\nche è solo un cambiamento.",
    media: [
      {
        type: "image",
        src: "specta/asset/optimized/specta1.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "specta/asset/optimized/specta4.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "specta/asset/optimized/specta5.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "specta/asset/optimized/specta6.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "specta/asset/optimized/specta7.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "specta/asset/optimized/specta2.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "specta/asset/optimized/specta3.webp",
        width: 1700,
        height: 1134,
      },
      {
        type: "video",
        src: "specta/asset/SPECTA-optimized.mp4",
        unmute: true,
      },
      {
        type: "image",
        src: "specta/asset/optimized/specta15.webp",
        width: 1700,
        height: 1133,
      },
      {
        type: "image",
        src: "specta/asset/optimized/specta16.webp",
        width: 1700,
        height: 1133,
      },
      {
        type: "image",
        src: "specta/asset/optimized/specta17.webp",
        width: 1700,
        height: 1133,
      },
      {
        type: "image",
        src: "specta/asset/optimized/specta18.webp",
        width: 1700,
        height: 1133,
      },
    ],
  },
  {
    slug: "iterations-inversions",
    sourcePage: "pixelpushing/",
    title: "Iterations/Inversions",
    categories: ["designerpage"],
    date: "2023",
    info: [
      'Features<br><a href="https://gpu.gallery/" target="_blank" rel="noopener noreferrer">Gpu Gallery</a>, 2023',
    ],
    description:
      "Iteration of a continuous inversion transformation of archival material, at the maximum frequency that the machine allows.",
    media: [
      {
        type: "image",
        src: "pixelpushing/asset/optimized/preview1.webp",
        width: 1920,
        height: 1080,
      },
      {
        type: "image",
        src: "pixelpushing/asset/optimized/preview2.webp",
        width: 1920,
        height: 1066,
      },
      {
        type: "video",
        src: "pixelpushing/asset/Iterationsinversions-optimized.mp4",
        unmute: false,
      },
      {
        type: "video",
        src: "pixelpushing/asset/istallationview-optimized.mp4",
        unmute: false,
      },
    ],
  },
  {
    slug: "corpo-macchina",
    sourcePage: "corpomacchina/",
    title: "Corpo macchina",
    categories: ["artistpage"],
    date: "2023",
    info: [
      'Links<br><a href="f.html" target="_blank" rel="noopener noreferrer">f.html (Generator)</a>',
    ],
    description:
      "These are photographs taken precisely at random: coordinates, time, height, orientation, rotations, and camera settings are randomly generated. The ranges of the coordinates correspond to a certain area, while the ranges of height, orientation, rotations, and settings correspond to the physical possibilities of the camera and tripod. Once the data has been generated, one has to go to the location corresponding to the coordinates, position the tripod according to the given height, orientation, and rotations, set the aperture, shutter speed, and ISO as described, and shoot at the appointed time.\n\nYou have to be a passive operator of the camera who becomes a photographer, author, body – you have to follow instructions – become a machine. The photo's metadata has been generated before they were taken. It is not the aesthetic will that dictates the data the machine produces, but it is the data the machine produces that dictates the aesthetic will.",
    media: [
      {
        type: "image",
        src: "corpomacchina/asset/optimized/cm1.webp",
        width: 1440,
        height: 1920,
      },
      {
        type: "video",
        src: "corpomacchina/asset/f-optimized.mp4",
        unmute: false,
      },
      {
        type: "image",
        src: "corpomacchina/asset/optimized/1a.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "corpomacchina/asset/optimized/2a.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "corpomacchina/asset/optimized/3a.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "corpomacchina/asset/optimized/4a.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "corpomacchina/asset/optimized/5a.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "corpomacchina/asset/optimized/6a.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "corpomacchina/asset/optimized/1.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "corpomacchina/asset/optimized/2.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "corpomacchina/asset/optimized/3.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "corpomacchina/asset/optimized/med.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "corpomacchina/asset/optimized/cm2.webp",
        width: 1440,
        height: 1920,
      },
      {
        type: "image",
        src: "corpomacchina/asset/optimized/z.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "corpomacchina/asset/optimized/z2.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "corpomacchina/asset/optimized/z3.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "corpomacchina/asset/optimized/i.webp",
        width: 1920,
        height: 1280,
      },
    ],
  },
  {
    slug: "monolite",
    sourcePage: "monolite/",
    title: "Monolite",
    categories: ["artistpage"],
    date: "2023",
    info: [],
    description:
      'Pen drive with its memory completely full. There is only one file .bit containing a sequence of precisely 256 billion digits "1". It is a monolith of data, containing no information other than that it is full.',
    media: [
      {
        type: "image",
        src: "monolite/asset/optimized/med.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "monolite/asset/optimized/2.webp",
        width: 1920,
        height: 1280,
      },
    ],
  },
  {
    slug: "due-dadi",
    sourcePage: "duedadi/",
    title: "Due dadi",
    categories: ["artistpage"],
    date: "2021",
    info: [],
    description:
      '12x12x12mm\n\nMade from two white plastic dice and then laser printed, they present themselves as altered objects, others: they are one alternative among many possible ones. Each thing could be any other, but it presents itself as absolute: "A miracle that does not amaze as much as it should: the hand has in truth less than six fingers, yet more than four" Szymborska, 1986).',
    media: [
      {
        type: "image",
        src: "duedadi/asset/optimized/med.webp",
        width: 1920,
        height: 1280,
      },
      {
        type: "image",
        src: "duedadi/asset/optimized/dadiscansioni1.webp",
        width: 1080,
        height: 1421,
      },
      {
        type: "image",
        src: "duedadi/asset/optimized/dadiscansioni2.webp",
        width: 1080,
        height: 1421,
      },
      {
        type: "image",
        src: "duedadi/asset/optimized/dadiscansioni3.webp",
        width: 1080,
        height: 1421,
      },
      {
        type: "image",
        src: "duedadi/asset/optimized/dadiscansioni4.webp",
        width: 1080,
        height: 1421,
      },
    ],
  },
];

const PROJECT_ORDER = [
  "digital-forest",
  "capsule-plaza",
  "n-cognitive-supremacy",
  "rhytuals",
  "off-discipline",
  "image-of-a-book",
];

window.PROJECTS.sort((first, second) => {
  const firstIndex = PROJECT_ORDER.indexOf(first.slug);
  const secondIndex = PROJECT_ORDER.indexOf(second.slug);
  const firstPosition = firstIndex === -1 ? PROJECT_ORDER.length : firstIndex;
  const secondPosition =
    secondIndex === -1 ? PROJECT_ORDER.length : secondIndex;
  return firstPosition - secondPosition;
});
