const columns=["id","name","entityType","field","period","based","country","tags","priority","instagram","website","notes","source","status"];
const labels={name:"name",entityType:"type",field:"field",based:"base",country:"country",tags:"tags",instagram:"instagram",website:"website"};
const base=(window.REALITIES_DATA||[]).map(row=>Object.fromEntries(columns.map((key,index)=>[key,row[index]||""])));
const italy=/italy|italia|milan|bergamo|brescia|rome|turin|bologna|florence|venice|naples|como|modena|perugia|treviso|trieste|bozen/i;
const baseTranslations={barcellona:"barcelona",bolzano:"bozen",firenze:"florence",genova:"genoa",milano:"milan",napoli:"naples",roma:"rome",torino:"turin",venezia:"venice",londra:"london",parigi:"paris",bruxelles:"brussels",copenaghen:"copenhagen",lisbona:"lisbon",stoccolma:"stockholm",varsavia:"warsaw",zurigo:"zurich",colonia:"cologne"};
const fieldTranslations={design:"visual",editoria:"editorial",interazione:"interaction",dati:"data",spaziale:"spatial"};
const normalizeDelimited=value=>[...new Set(String(value||"").toLowerCase().split(",").map(item=>item.trim().replace(/\s+/g," ")).filter(Boolean))].join(", ");
const translateDelimited=(value,translations)=>normalizeDelimited(value).split(", ").map(item=>translations[item]||item).filter(Boolean).join(", ");
const normalizeArchiveRecord=record=>({...record,based:translateDelimited(record.based,baseTranslations),field:translateDelimited(record.field,fieldTranslations),tags:normalizeDelimited(record.tags)});
const categories={studios:r=>r.entityType==="Studio",agencies:r=>r.entityType==="Agency",designers:r=>r.entityType==="Person",artists:r=>r.entityType==="Artist",foundries:r=>r.entityType==="Foundry",platforms:r=>r.entityType==="Platform",collectives:r=>r.entityType==="Collective",courses:r=>r.entityType==="Course",publishers:r=>r.entityType==="Publisher",showcases:r=>r.entityType==="Showcase",tools:r=>r.entityType==="Tool"};
const locations={italy:r=>italy.test(r.based),abroad:r=>Boolean(r.based)&&!italy.test(r.based)};
const entityTypes=[["Studio","studios"],["Agency","agencies"],["Person","designers"],["Artist","artists"],["Foundry","foundries"],["Platform","platforms"],["Collective","collectives"],["Course","courses"],["Publisher","publishers"],["Showcase","showcases"],["Tool","tools"]];
let overrides=JSON.parse(localStorage.getItem("realities-overrides")||"{}"),mediaCache={},records=[],activeCategory="studios",activeLocation=null,starredOnly=false,showHidden=false,editingId=null,pendingImageSlots=[],deletedImageSlots=[];
const apiRoot=location.port==="5501"?"http://127.0.0.1:4173":"";
const hasLocalApi=Boolean(apiRoot)||(location.hostname==="127.0.0.1"&&location.port==="4173");
const overridesEndpoint=hasLocalApi?`${apiRoot}/api/overrides`:"archive-overrides.json";
const iframeMode=location.pathname.endsWith("index-iframe.html");
const grid=document.querySelector("#grid"),search=document.querySelector("#search"),template=document.querySelector("#card-template"),editor=document.querySelector("#editor"),form=document.querySelector("#edit-form");
async function loadOverrides(){try{const localOverrides=Object.fromEntries(Object.entries(overrides).map(([id,record])=>[id,normalizeArchiveRecord(record)])),response=await fetch(overridesEndpoint);if(!response.ok)return;const remoteOverrides=Object.fromEntries(Object.entries(await response.json()).map(([id,record])=>[id,normalizeArchiveRecord(record)])),browserIsSource=Boolean(apiRoot&&Object.keys(localOverrides).length),merged=browserIsSource?{...remoteOverrides,...localOverrides}:remoteOverrides;if(browserIsSource&&JSON.stringify(merged)!==JSON.stringify(remoteOverrides)){overrides=merged;await persist()}else overrides=remoteOverrides}catch{}}
async function loadMediaCache(){try{const response=await fetch("instagram-cache.json");if(response.ok)mediaCache=await response.json()}catch{}}
function rebuild(){records=base.filter(r=>!overrides[r.id]?.deleted).map(r=>({...r,...(overrides[r.id]||{})}));Object.values(overrides).filter(r=>r.isNew&&!r.deleted).forEach(r=>records.push(r));renderFilters();render()}
async function persist(){localStorage.setItem("realities-overrides",JSON.stringify(overrides));if(!hasLocalApi)return;try{await fetch(overridesEndpoint,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(overrides)})}catch{}}
async function syncWorkbook(){if(!hasLocalApi)return;try{const response=await fetch(`${apiRoot}/api/sync-excel`,{method:"POST"});if(!response.ok)throw new Error();console.info("Excel synced")}catch{console.info("Run: node scripts/sync-archive-xlsx.mjs")}}
function addFilters(target,options,active,setActive){target.replaceChildren(...Object.keys(options).map(label=>{const button=document.createElement("button");button.type="button";button.className=`filter-button ${label===active?"active":""}`;button.textContent=label;button.onclick=()=>{setActive(label);renderFilters();render()};return button}))}
function renderFilters(){const globalSearch=Boolean(search.value.trim());addFilters(document.querySelector("#category-filters"),categories,globalSearch?null:activeCategory,label=>activeCategory=label===activeCategory?null:label);const locationFilters=document.querySelector("#location-filters"),star=document.querySelector("#star-filter"),hide=document.querySelector("#hide-filter");addFilters(locationFilters,locations,globalSearch?null:activeLocation,label=>activeLocation=label===activeLocation?null:label);locationFilters.append(star,hide);star.classList.toggle("active",!globalSearch&&starredOnly);star.setAttribute("aria-pressed",String(starredOnly));star.onclick=()=>{starredOnly=!starredOnly;renderFilters();render()};hide.classList.toggle("active",showHidden);hide.setAttribute("aria-pressed",String(showHidden));hide.onclick=()=>{showHidden=!showHidden;renderFilters();render()}}
function instagramHandle(url){try{return `@${new URL(url).pathname.split("/").filter(Boolean)[0]||"instagram"}`}catch{return "@instagram"}}
function enableLongPress(element,record){let timer;let opened=false;const clear=()=>{clearTimeout(timer);timer=null};element.addEventListener("pointerdown",event=>{if(event.target.tagName==="A")return;opened=false;timer=setTimeout(()=>{opened=true;openEditor(record)},550)});element.addEventListener("pointerup",clear);element.addEventListener("pointerleave",clear);element.addEventListener("pointercancel",clear);element.addEventListener("dblclick",event=>{event.preventDefault();event.stopPropagation();openEditor(record)});element.addEventListener("click",event=>{if(opened){event.preventDefault();event.stopPropagation();opened=false}})}
function siteFavicon(url){try{return `https://www.google.com/s2/favicons?sz=64&domain_url=${encodeURIComponent(new URL(url).origin)}`}catch{return ""}}
function renderMedia(media,record){const destination=record.website||record.instagram;if(destination){let clickTimer;media.tabIndex=0;media.setAttribute("role","link");media.onclick=()=>{clickTimer=setTimeout(()=>window.open(destination,"_blank","noopener"),220)};media.ondblclick=event=>{clearTimeout(clickTimer);event.preventDefault()};media.onkeydown=event=>{if(event.key==="Enter")window.open(destination,"_blank","noopener")}}const instagramItems=record.instagram?mediaCache[instagramHandle(record.instagram).slice(1)]||[]:[];const localItems=instagramItems.length?instagramItems:mediaCache[`record:${record.id}`]||[];if(iframeMode&&instagramItems.length){media.classList.add("iframe-media");media.replaceChildren(...instagramItems.slice(0,4).map(item=>{const frame=document.createElement("iframe");frame.src=`${item.permalink.replace(/\/$/,"")}/embed/`;frame.title=record.name;frame.loading="lazy";frame.referrerPolicy="strict-origin-when-cross-origin";return frame}));return}media.replaceChildren(...localItems.slice(0,4).map(item=>{const image=document.createElement("img");image.src=item.imageUrl;image.alt="";image.loading="lazy";return image}))}
function siteLabel(url){try{return new URL(url).hostname.replace(/^www\./,"")}catch{return url.replace(/^https?:\/\//,"").replace(/\/$/,"")}}
function render(){const term=search.value.trim().toLowerCase(),globalSearch=Boolean(term);const shown=records.filter(r=>(showHidden||!r.hidden)&&(globalSearch||!activeCategory||categories[activeCategory](r))&&(globalSearch||!activeLocation||locations[activeLocation](r))&&(globalSearch||!starredOnly||r.starred)).filter(r=>!term||[r.name,r.entityType,r.field,r.based,r.tags].join(" ").toLowerCase().includes(term));grid.replaceChildren();if(!shown.length){grid.innerHTML='<p class="empty">no records</p>';return}for(const record of shown){const card=template.content.cloneNode(true);card.querySelector("h2").textContent=record.name;card.querySelector(".card-tags").textContent=[record.based,record.tags].filter(Boolean).join(" — ");const links=card.querySelector(".card-links");if(record.instagram){const a=document.createElement("a");a.href=record.instagram;a.target="_blank";a.rel="noreferrer";a.textContent=instagramHandle(record.instagram);links.append(a)}if(record.website){const a=document.createElement("a");a.href=record.website;a.target="_blank";a.rel="noreferrer";const icon=document.createElement("img");icon.className="site-favicon";icon.src=siteFavicon(record.website);icon.alt="";a.append(icon,siteLabel(record.website));links.append(a)}const article=card.querySelector("article");renderMedia(card.querySelector(".card-media"),record);enableLongPress(article,record);grid.append(card)}}
function makeInput(key,record){const label=document.createElement("label");label.textContent=labels[key]||key;if(key==="entityType"){const select=document.createElement("select");select.name=key;select.append(new Option("",""),...entityTypes.map(([value,label])=>new Option(label,value)));select.value=record[key]||"";label.append(select);return label}if(key==="starred"){label.textContent="";const input=document.createElement("input");input.name=key;input.type="checkbox";input.hidden=true;input.checked=Boolean(record.starred);const star=document.createElement("button");star.type="button";star.className="star-picker";star.textContent="★";star.classList.toggle("active",input.checked);star.onclick=()=>{input.checked=!input.checked;star.classList.toggle("active",input.checked)};label.append(input,star);return label}if(key==="images"){const handle=instagramHandle(record.instagram||"").slice(1),items=mediaCache[handle]||[],slots=document.createElement("div");slots.className="manual-media-grid";const renderSlot=index=>{const slot=slots.children[index];slot.querySelector("img")?.remove();const file=pendingImageSlots[index],source=!deletedImageSlots[index]&&(file instanceof File?URL.createObjectURL(file):items[index]?.imageUrl);if(source){const image=document.createElement("img");image.src=source;image.alt="";slot.prepend(image)}};for(let index=0;index<4;index+=1){const slot=document.createElement("label"),input=document.createElement("input");let pressTimer,deletedByPress=false;slot.className="manual-media-slot";input.type="file";input.multiple=true;input.accept="image/*";input.onchange=()=>{Array.from(input.files||[]).slice(0,4-index).forEach((file,offset)=>{pendingImageSlots[index+offset]=file;deletedImageSlots[index+offset]=false});for(let slotIndex=index;slotIndex<4;slotIndex+=1)renderSlot(slotIndex);input.value=""};slot.addEventListener("pointerdown",()=>{if(!items[index]&&!pendingImageSlots[index])return;deletedByPress=false;pressTimer=setTimeout(()=>{deletedImageSlots[index]=true;pendingImageSlots[index]=null;deletedByPress=true;renderSlot(index)},1000)});["pointerup","pointerleave","pointercancel"].forEach(event=>slot.addEventListener(event,()=>clearTimeout(pressTimer)));slot.addEventListener("click",event=>{if(deletedByPress){event.preventDefault();event.stopPropagation();deletedByPress=false}},true);slot.append(input);slots.append(slot);renderSlot(index)}label.append(slots);return label}const input=document.createElement("input");input.name=key;input.value=record[key]||"";if(["field","based","tags"].includes(key)){const id=`suggestions-${key}`;let list=document.querySelector(`#${id}`);if(!list){list=document.createElement("datalist");list.id=id;const values=[...new Set(records.flatMap(r=>key==="tags"?(r.tags||"").split(/,\s*/):[r[key]]).filter(Boolean))].sort();list.replaceChildren(...values.map(value=>new Option(value)));document.body.append(list)}input.setAttribute("list",id)}label.append(input);return label}
function openEditor(record){editingId=record.id;pendingImageSlots=Array(4).fill(null);deletedImageSlots=Array(4).fill(false);const fields=document.querySelector("#form-fields");fields.replaceChildren(...["name","starred","entityType","field","based","tags","instagram","website","images"].map(key=>makeInput(key,record)));fields.querySelector(".star-picker")?.closest("label")?.prepend("favourite");document.querySelector("#delete-record").hidden=!records.some(r=>r.id===record.id);editor.showModal()}
async function uploadManualMedia(record,slots){if(!slots.some(file=>file instanceof File&&file.size)&&!deletedImageSlots.some(Boolean))return;const handle=instagramHandle(record.instagram).slice(1),category=Object.keys(categories).find(key=>categories[key](record));if(handle==="instagram"||!category||!record.name)throw new Error("add name, type and instagram before images");const previous=mediaCache[handle]||[],posts=[];for(const [index,file] of slots.entries()){if(deletedImageSlots[index])continue;if(file instanceof File&&file.size){const params=new URLSearchParams({handle,category,name:record.name,slot:String(index+1)});const response=await fetch(`${apiRoot}/api/manual-media?${params}`,{method:"PUT",headers:{"Content-Type":file.type||"image/jpeg"},body:file});if(!response.ok)throw new Error("image upload failed");posts[index]=await response.json()}else if(previous[index])posts[index]=previous[index]}const saved=await fetch(`${apiRoot}/api/instagram-cache`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({handle,posts:posts.filter(Boolean)})});if(!saved.ok)throw new Error("image cache update failed");mediaCache[handle]=posts.filter(Boolean)}
form.addEventListener("submit",async event=>{event.preventDefault();const data=new FormData(form),slots=[...pendingImageSlots];const values=normalizeArchiveRecord(Object.fromEntries(data));values.starred=form.elements.starred.checked;await uploadManualMedia(values,slots);const previous=records.find(r=>r.id===editingId)||{};overrides[editingId]={...previous,...values,isNew:!base.some(r=>r.id===editingId)};await persist();editor.close();rebuild()});
function openNewRecord(){openEditor({id:`NEW-${Date.now()}`,name:"",entityType:"",field:"",based:"",tags:"",instagram:"",website:"",period:"Contemporary",status:"To verify",source:"Website entry",priority:"",notes:""})}
document.querySelector("#cancel-edit").onclick=()=>editor.close();document.querySelector("#delete-record").onclick=async()=>{overrides[editingId]={...(overrides[editingId]||{}),deleted:true};await persist();editor.close();rebuild()};editor.addEventListener("click",event=>{if(event.target===editor)editor.close()});search.addEventListener("input",()=>{renderFilters();render()});search.addEventListener("dblclick",event=>{event.preventDefault();openNewRecord()});document.querySelector("#back-to-top").onclick=()=>window.scrollTo({top:0,behavior:"auto"});let lastScrollY=window.scrollY,navBoundary=0;const controls=document.querySelector(".controls"),controlsSpacer=document.querySelector("#controls-spacer");function setFixedNav(fixed){if(fixed===document.body.classList.contains("nav-fixed"))return;if(fixed){controlsSpacer.style.height=`${controls.offsetHeight}px`;document.body.classList.add("nav-fixed")}else{document.body.classList.remove("nav-fixed");controlsSpacer.style.height="0px"}}function updateFixedNav(){navBoundary=navBoundary||controls.getBoundingClientRect().bottom+window.scrollY;const scrollingUp=window.scrollY<lastScrollY;setFixedNav(window.scrollY>navBoundary&&scrollingUp);lastScrollY=window.scrollY}window.addEventListener("scroll",updateFixedNav,{passive:true});let holdTimer;search.addEventListener("pointerdown",()=>{holdTimer=setTimeout(openNewRecord,650)});["pointerup","pointerleave","pointercancel"].forEach(event=>search.addEventListener(event,()=>clearTimeout(holdTimer)));const openEditorBase=openEditor;const makeHideField=record=>{const label=document.createElement("label"),input=document.createElement("input"),button=document.createElement("button");label.textContent="hide";input.name="hidden";input.type="checkbox";input.hidden=true;input.checked=Boolean(record.hidden);button.type="button";button.className="hide-picker";button.textContent="—";button.classList.toggle("active",input.checked);button.onclick=()=>{input.checked=!input.checked;button.classList.toggle("active",input.checked)};label.append(input,button);return label};openEditor=record=>{openEditorBase(record);document.querySelector("#form-fields").insertBefore(makeHideField(record),document.querySelector("#form-fields").children[2]||null)};form.addEventListener("submit",()=>{if(!form.elements.hidden?.checked){const record=records.find(item=>item.id===editingId);if(record)record.hidden=false}},true);Promise.all([loadOverrides(),loadMediaCache()]).then(rebuild);
document.addEventListener("keydown",async event=>{if(!(event.metaKey||event.ctrlKey)||event.key.toLowerCase()!=="s")return;event.preventDefault();await persist();await syncWorkbook()});
